version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory:  /var/tmp
    docker:
      - image: diegovalle/elcrimen-docker
        auth:
          username: diegovalle  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - checkout
      - run:
          name: Build the website https://elcri.men
          command: |
            bash -c "cd ~/new.crimenmexico/ansible/ && echo $ANSIBLE_PASSWORD > password.txt && ansible-playbook -c local ssh.yml --vault-password-file=~/new.crimenmexico/ansible/password.txt --extra-vars 'secrets=true' && cd ~/new.crimenmexico && git config --global url.'https://github.com/'.insteadOf git@github.com: && git config --global url.'https://'.insteadOf git:// && git pull && make"
          no_output_timeout: 2400

#      - store_artifacts:
#          path: /root/new.crimenmexico/db/crimenmexico.db
#          destination: crimenmexico.db
