name: GitHub Actions Demo
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  Build-Elcrimen:
    runs-on: ubuntu-latest
    container:
      image: diegovalle/elcrimen-docker
      options:  --workdir /home/rstudio/new.crimenmexico --user rstudio
      credentials:
        username: diegovalle
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      env:
        ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        IPADDRESS: ${{ secrets.IPADDRESS }}
        NETLIFYAPIKEY: ${{ secrets.NETLIFYAPIKEY }}
        SEMAPHORE_API_TOKEN: ${{ secrets.SEMAPHORE_API_TOKEN }}
        SEMAPHORE_PROJECT_ID: ${{ secrets.SEMAPHORE_PROJECT_ID }}
        SEMAPHORE_REF: ${{ secrets.SEMAPHORE_REF }}
        HOME: "/home/rstudio"
    steps:
      - name: What OS is running
        run: uname -a
      - name: Print current dir
        run: echo "$PWD"
      - name: Print R version
        run: echo "$(R --version)"
      - name: Build the website https://elcri.men
        run: |
          bash -c "export HOME=/home/rsutido && cd ~/new.crimenmexico/ansible/ && echo $ANSIBLE_PASSWORD > password.txt && ansible-playbook -c local ssh.yml --vault-password-file=~/new.crimenmexico/ansible/password.txt --extra-vars 'secrets=true' && cd ~/new.crimenmexico && git config --global url.'https://github.com/'.insteadOf git@github.com: && git config --global url.'https://'.insteadOf git:// && git pull && make"
      - run: echo "🍏 This job's status is ${{ job.status }}."
